nginx:
  image: nginx
  container_name: nginx
  volumes:
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /volumes/foobot/certs:/etc/nginx/certs:ro
  ports:
    - '80:80'
    - '443:443'
    
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  
letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /volumes/foobot/certs:/etc/nginx/certs:rw
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    
    
api:
  image: 'dorsaydevelopment/foobot:dev'
  container_name: api
  links:
    - db
  volumes:
    - ./conf.d/:/etc/nginx/conf.d
    - /volumes/foobot/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - FOOBOT_DB_CONN=mongodb://db/foobot
    - FOOBOT_URL=https://foobot.dorsaydevelopment.ca/webhook
    - FOOBOT_TOKEN=223951341:AAGsPCHjO44E9OEHEvWMtUS3k73l4KKXoRQ
    - FOOBOT_GOOGLE_FLIGHTS_KEY=AIzaSyAETu5_M7s9w8a1g2YE-FwBuHvbTHP1u7A
    - FOOBOT_PORT=80
    - FOOBOT_LOG_LEVEL=info
    - FOOBOT_LOG_DIR=/src/logs
    - FOOBOT_MESSENGER_PAGE_ACCESS_TOKEN=EAAYrLA0uYyIBAC6Psnm2bZCZAQOGp0CySEP6mlCJZBh75VwTGuP9ZAwlsHhWVmGPeP5aN20tSteUOXy20OXCERBjm9kvkhUTRJRDBaX1yjU6VEY2wDa8YOZBlUIO8b4XUYLWAN0gNZADZCiWPJxqtwDsq7jITNgjeS1W1ldIrLi3gZDZD
    - FOOBOT_MESSENGER_WEBHOOK_TOKEN="skf&ueo0999#J$v.#mm?)23gas4$5vJK!=ka+`/3hf"
    - VIRTUAL_HOST=foobot.dorsaydevelopment.ca
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=foobot.dorsaydevelopment.ca
    - LETSENCRYPT_EMAIL=dorsay@live.ca
    - LETSENCRYPT_TEST=false
  restart: always

db:
  image: 'mongo:latest'
  container_name: db
  volumes:
    - /volumes/foobot/db:/data/db
  ports:
    - '27017:27017'

watchtower:
  image: 'centurylink/watchtower:latest'
  container_name: watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock